name: Deploy to aaPanel Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy changed files via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 199.192.31.32
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: "./"
          server-dir: "/"

          exclude: |
            __MACOSX/**
            .git/**
            **/.git*
            **/.env
            **/*.env
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/.github/**
            **/.DS_Store


          dry-run: false
